name: Extend CoreOS image

on:
  push:
    branches: [ "main" ]
    tags:        
      - '*' 
  pull_request:
    branches: [ "main" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extend the base qcow2 image amd64
      run: docker run -v $(pwd):/work $(echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} | awk '{print tolower($0)}'):image-installer-0.1.0 /entrypoint.sh https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/36.20220906.3.2/x86_64/fedora-coreos-36.20220906.3.2-qemu.x86_64.qcow2.xz
    - name: Compress image
      run: sudo xz *.qcow2 
    - uses: actions/upload-artifact@v3
      with:
        path: "*.qcow2.xz"
  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-qemu-action@v2
      name: Set up QEMU
      with:
        platforms: arm64
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extend the base qcow2 image arm64
      run: docker run --platform linux/arm64 -v $(pwd):/work $(echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} | awk '{print tolower($0)}'):image-installer-0.1.0 tar cf - /assets | docker run -i --platform linux/amd64 -v $(pwd):/work $(echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} | awk '{print tolower($0)}'):image-installer-0.1.0 bash -c "tar xf - -C / && /entrypoint.sh https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/36.20220906.3.2/aarch64/fedora-coreos-36.20220906.3.2-qemu.aarch64.qcow2.xz"
    - name: Compress image
      run: sudo xz *.qcow2 
    - uses: actions/upload-artifact@v3
      with:
        path: "*.qcow2.xz"
  release:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
    - uses: softprops/action-gh-release@v1
      name: Release
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "artifact/*.qcow2.xz"